mysql:
  host: 'localhost'
  port: 3306
  database: 'jozelot_network'
  user: ''
  password: ''

# CACHE
redis:
  host: 'localhost'
  port: 6379
  password: ''


color_settings:
  primary: '#00A4FC'
  secondary: '#00FC00'
  tertiary: '#FCE300'
  danger: '#f90036'
  grey: '#A8A8A8'


items:
  navigator:
    name: '<!italic><gold>Navigator'
    item: COMPASS
    slot: 4
    description:
      - ''
      - '<!italic><gray>Hier kannst du auswählen'
      - '<!italic><gray>auf welchen Server du spielen möchtest'

  gamemode_changer:
    name_s: '<!italic><dark_purple>Survival'
    name_sp: '<!italic><blue>Spectator'
    item: ENDER_EYE
    slot: 1
    description:
      - ''
      - '<!italic><gray>Wechle schnell zwischen'
      - '<!italic><gray>Survival und Spectator'

  player_hider:
    visible_name: '<!italic><green>Spieler sichtbar'
    hidden_name: '<!italic><red>Spieler versteckt'
    team_name: '<!italic><dark_purple>Server Team sichtbar'
    visible_item: LEATHER_HELMET
    hidden_item: LEATHER_HELMET
    team_item: LEATHER_HELMET
    slot: 7
    description:
      - ''
      - '<!italic><gray>Verstecke andere Spieler'

  back_arrow:
    name: '<!italic><gray>Zurück'

  previous_page:
    name: '<!italic><gray>Letzte Seite'

  next_page:
    name: '<!italic><gray>Nächste Seite'

  current_page:
    name: '<!italic><gray>Seite '

  spawn_button:
    name: '<!italic><gold>Spawn'
    item: MAGMA_CREAM

  sort_button:
    name: '<!italic><aqua>Sortierung'

  world_change:
    overworld_item: GRASS_BLOCK
    nether_item: NETHERRACK
    end_item: END_STONE
    overworld_name: "<!italic><white>Overworld"
    nether_name: "<!italic><white>Nether"
    end_name: "<!italic><white>End"
    lore:
      - ""
      - "<!italic><gray>Klicke um dich in diese"
      - "<!italic><gray>Welt zu teleportieren"

  location_overview:
    name: '<!italic><blue>Locations'
    item: DECORATED_POT
    slot: 21
    description:
      - ""
      - "<!italic><gray>Hier siehst du eine"
      - "<!italic><gray>Übersicht über alle wichtigen"
      - "<!italic><gray>Orte dieses Projektes"
      - ""
      - "<!italic><dark_gray>» <gray>Anzahl: <white>{location_count}"

  player_overview:
    name: '<!italic><red>Spieler'
    item: ARMOR_STAND
    slot: 23
    description:
      - ""
      - "<!italic><gray>Hier siehst du eine"
      - "<!italic><gray>Übersicht über alle Spieler"
      - "<!italic><gray>dieses Projektes"
      - ""
      - "<!italic><dark_gray>» <gray>Anzahl: <white>{player_count}"


  project_overview:
    name: '<!italic><gold>Projekt Informationen'
    item: LECTERN
    slot: 13
    description:
      - ""
      - "<!italic><gray>Hier siehst du alle"
      - "<!italic><gray>wichtigen Informationen"
      - "<!italic><gray>zu diesem Projekt"
      - ""
      - "<!italic><dark_gray>» <gray>Name: <white>EventAttack"
      - "<!italic><dark_gray>» <gray>Jahr: <white>Winter 2024"
      - "<!italic><dark_gray>» <gray>Owner: <white>TFJ"
      - "<!italic><dark_gray>» <gray>Hoster: <white>RedWolf"

inventories:
  navigator:
    title: "Navigator"
    size: 45

  location_overview:
    title: "Location Übersicht"

  player_overview:
    title: "Spieler Übersicht"
    size: 45

  location_menu:
    title: "Location: "
    size: 27