# +-------------------------------------------------------+
# |                                                       |
# |                   JOZELOT PROXY                       |
# |             Netzwerk Core Steuerung                   |
# |                                                       |
# +-------------------------------------------------------+

# GENERAL
network-name: 'jozelot.de'
brand-name: '§b§ljozelot.de§r'
lobby-server: 'lobby'
tab-refresh-time: 1

# LINKS & MEDIA
server-links:
  - |
    <#f90036><b>Webseite
    https://jozelot.de
  - |
    <#7289DA><b>Discord
    https://jozelot.de/discord
  - |
    <#00A4FC><b>Hosting
    https://panel.jozelot.de

# VERSION CONTROL
protocol-versions:
  min: 767          # 1.20.4
  recommended: 773  # 1.21.3
  max: 774          # 1.21.4

# PUNISHMENT SYSTEM
punishment-reasons:
  - "101 Hacking"
  - "102 Killaura"
  - "103 Movement"
  - "104 X-Ray"
  - "105 AutoClicker"
  - "106 Reach"
  - "107 Unfairer Vorteil"
  - "201 Beleidigung"
  - "202 Schwere Beleidigung"
  - "203 Rassismus"
  - "204 Spamming"
  - "205 Werbung"
  - "206 Provokation"
  - "207 Wortwahl"
  - "208 Drohung"
  - "209 Radikalismus"
  - "301 Griefing"
  - "302 Scamming"
  - "303 Trolling"
  - "304 Bug Using"
  - "401 Unangemessener Name"
  - "402 Unangemessener Skin"
  - "403 Ban Umgehung"
  - "404 Account Sicherheit"
  - "405 Vortäuschen von Rechten"
  - "406 Sicherheit-Bann"

# SECURITY & COMMAND BLOCKER
blocked-commands:
  hard-blocked:
    - "/op"
    - "/deop"
    - "/stop"
    - "/reload"
    - "/rl"
    - "/ban-ip"
    - "/?"
    - "/help"
    - "/ver"
    - "/about"
    - "/icanhasbukkit"
    - "/luckperms"
    - "/perm"
    - "/permission"
    - "/perms"
    - "/permissions"
    - "/luckpermsvelocity"
    - "/teammsg"
    - "/pardon"
    - "/pardon-ip"
    - "/w"
    - "/me"
    - "/voicechat"
    - "/voicechatproxy"
    - "/fastasyncworldedit"
    - "/we"

  # Permission: network.commands.bypass.<group>
  groups:
    building:
      commands: ["/headdatabase", "/headdb", "/headmenu", "/hdb"]
    worldedit:
      commands: ["/worldedit", "/fawe"]
    admin:
      commands: ["/lp", "/lpv", "/plugins", "/pl", "/trigger", "/mv"]
    moderator:
      commands: ["/version"]

# INFRASTRUCTURE
pterodactyl:
  url: "https://panel.jozelot.de"
  api-key: "KEY"

mysql:
  host: 'localhost'
  port: 3306
  database: 'jozelot_network'
  user: ''
  password: ''

redis:
  host: 'localhost'
  port: 6379
  password: ''

# DESIGN
color-settings:
  primary: '#00A4FC'
  secondary: '#00FC00'
  tertiary: '#FCE300'
  danger: '#f90036'
  grey: '#A8A8A8'

# +-------------------------------------------------------+
# |                 PERMISSION OVERVIEW                   |
# +-------------------------------------------------------+
# network.command.reload | .lobby | .clearchat | .find
# network.get.logs
# network.clearchat.bypass
# network.network.manage (.server.start/stop/restart/status)
# network.maintenance.bypass.all | .<server>
# network.forcedhost.all | .<server>
# network.command.ban | .unban | .banlist | .kick | .mute | .unmute | .mutelist
# network.command.vanish | .vanish.other
# network.vanish.see-all
# network.vanish.see-team
# network.ban.bypass
# network.command.tpo | .tpohere | .send | .server
# network.command.whitelist | network.whitelist.bypass
# network.command.playtime | .admin
# network.command.broadcast
# network.maxplayers.bypass.all | .<server>
# network.command.msg | .gmsg | .global | .reply
# network.chat.minimessage
# network.command.playerinfo | .spy | .mods | .client | .version
#
# BACKEND UTILS:
# network.utils.command.fly (.others / .all)
# network.utils.join.fly
# network.utils.command.gamemode | .heal | .god | .spec (.others)
# network.utils.admin.build | .inventory
# network.utils.command.spawn | .setspawn

# network.lobby.player_hider.team