name: JavaDoc Deployment

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      # Hier fügst du alle Ordnernamen deiner Projekte hinzu
      matrix:
        project: [JozelotProxy, JozelotLobby, JozelotUtils]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Generate JavaDoc
        # Wir führen mvn im jeweiligen Unterordner aus
        run: mvn javadoc:javadoc -f ${{ matrix.project }}/pom.xml

      - name: Deploy to Nginx via SSH
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          # Dynamische Pfade basierend auf dem Projektnamen
          SOURCE: "docs/${{ matrix.project }}/"
          TARGET: "/var/www/docs.jozelot.de/pages/main/jd/${{ matrix.project }}"
          ARGS: "-rlgoDzvc -i --delete"